#!/usr/bin/with-contenv bash

source /etc/env

echo "
RUNNING ENVIRONMENT
-----------------------------------------------
PUID           | $PUID
PGID           | $PGID
-----------------------------------------------
"

groupmod -o -g "$PGID" deluge
usermod -o -u "$PUID" deluge

chown -R /config /downloads 
