#!/usr/bin/with-contenv bash
# shellcheck shell=bash

echo "
RUNNING ENVIRONMENT
-----------------------------------------------
PUID           | $PUID
PGID           | $PGID
-----------------------------------------------
"
