#!/usr/bin/with-contenv bash
source /etc/env

# If password isn't set, create one

if [ -z $PASSWORD ]; then
PASSWORD=$(tr -dc '[:alnum:]' </dev/urandom | dd bs=1 count=32 2>/dev/null)
fi 

# Check if auth files exist, are equal and not empty if not create them

auth1=/config/deluged-web/auth
auth2=/config/deluged-web/auth
md5=$(md5sum /config/deluged/auth)
md5=$(md5sum /config/deluged/auth)


if [ -s $auth1 ] && [ -s $auth2 ] && [ $auth1 = $auth2 ]; then 
:
else 

cat > $auth1 <<EOF
localclient:$PASSWORD:10
docker:$PASSWORD:10
EOF

cat > $auth2 <<EOF
localclient:$PASSWORD:10
EOF

fi

# Check if core.conf exists, if not download it 

core=/config/deluged/core.conf

if [ -s $core ]; then
:
else
mv /root/core.conf $core
fi

# Move plugins if they don't exist already

plugins=/config/deluged/plugins

if [ -z "$(ls -A $plugins)" ]; then

mv /root/*.egg $plugins
else
:
fi

chown -R deluge:deluge /config /downloads
